# Uncomment the next line to define a global platform for your project
use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

target 'KinescopeExample' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for KinescopeExample
  pod 'ReactiveDataDisplayManager', '~> 7.0.0-beta'
  pod 'Kingfisher', '~> 6.2.1'
  pod 'KinescopeSDK', :path => '../'

end

# fixes iOS 12.0 build
post_install do |installer|
  puts "-- post install --"
    installer.pods_project.targets.each do |target|
        if target.name == "KinescopeSDK"
            puts "Updating #{target.name} OTHER_LDFLAGS"
            target.build_configurations.each do |config|
              puts "Updating #{config} OTHER_LDFLAGS"
                xcconfig_path = config.base_configuration_reference.real_path
                xcconfig = File.read(xcconfig_path)
                new_xcconfig = xcconfig.sub('OTHER_LDFLAGS = $(inherited)', 'OTHER_LDFLAGS = $(inherited) -weak_framework "AVFoundation"')
                File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
            end
        end
    end
    puts "-- post install --"
end
