# Uncomment the next line to define a global platform for your project
use_frameworks!
platform :ios, '10.0'

target 'KinescopeExample' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for KinescopeExample
  pod 'ReactiveDataDisplayManager', :git => 'https://github.com/surfstudio/ReactiveDataDisplayManager', :tag => '7.0.0-beta'
  pod 'KinescopeSDK', :path => '../'

end
