#!/usr/bin/env bash

# regex to add task identifier from branch name to commit msg
BRANCHNAME=$(git branch | grep '*' | sed 's/* //' | cut -f1,2 -d'-')
NAME="${BRANCHNAME#*dev/}"

DESCRIPTION=$(git config branch."$NAME".description)

echo "$NAME"': '$(cat "$1") > "$1"
if [ -n "$DESCRIPTION" ]
then
   echo "" >> "$1"
   echo $DESCRIPTION >> "$1"
fi
