# Uncomment the next line to define a global platform for your project
use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

def common_pods
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoSwiftyM3U8', '~> 1.0.0'
end

target 'KinescopeSDK' do
  common_pods
end


target 'KinescopeSDKTests' do
  common_pods
end

post_install do |installer|
  puts "-- post install --"
    installer.pods_project.targets.each do |target|
        if target.name == "Pods-KinescopeSDK"
            puts "Updating #{target.name} OTHER_LDFLAGS"
            target.build_configurations.each do |config|
              puts "Updating #{config} OTHER_LDFLAGS"
                xcconfig_path = config.base_configuration_reference.real_path
                xcconfig = File.read(xcconfig_path)
                new_xcconfig = xcconfig.sub('OTHER_LDFLAGS = $(inherited)', 'OTHER_LDFLAGS = $(inherited) -weak_framework "AVFoundation"')
                File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
            end
        end
    end
    puts "-- post install --"
end
