# Uncomment the next line to define a global platform for your project
use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

def common_pods
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoSwiftyM3U8', '~> 1.0.0'
end

target 'KinescopeSDK' do
  common_pods
end

target 'KinescopeSDKTests' do
  common_pods
end
